import i18n from 'i18next';

const dictionary: Record<string, string> = {
  // Navigation / Tabs / Sidebar
  "Portfel": "Wallet",
  "Historia": "History",
  "Wyloguj się": "Log Out",
  "Zaloguj się": "Log In",
  "Profil: Publiczny": "Profile: Public",
  "Profil: Prywatny": "Profile: Private",
  "Kliknij, aby ukryć profil": "Click to make private",
  "Kliknij, aby upublicznić": "Click to make public",
  "Odłącz Githuba": "Disconnect GitHub",
  "Podłącz Githuba!": "Connect GitHub!",
  "Konto": "Account",
  "Saldo": "Balance",
  "Freebet": "Freebet",
  "Społeczność": "Community",
  "Wszyscy": "All",
  "Obserwujący mnie": "Followers",
  "Obserwowani": "Followed",
  "Obserwuj": "Follow",
  "Przestań obserwować": "Unfollow",
  "Brak obserwowanych": "No followed users",
  "Brak obserwujących": "No followers",
  
  // Wallet
  "Zasilenie konta": "Deposit",
  "Wypłata": "Withdrawal",
  "Kwota (PLN)": "Amount (PLN)",
  "Zasil konto": "Deposit",
  "Wypłać środki": "Withdraw",
  "Wprowadź poprawną kwotę": "Enter a valid amount",
  "Zlecono wypłatę": "Withdrawal requested",
  "Zlecono doładowanie": "Deposit requested",
  "Historia transakcji": "Transaction History",
  "Brak transakcji": "No transactions",
  "Doładuj konto": "Top Up",
  "Wypłać": "Withdraw",
  "Zasil": "Deposit",
  "Stan konta": "Account Status",
  "Podsumowanie": "Summary",
  "Saldo główne": "Main Balance",
  "Dostępne do obstawiania": "Available for betting",
  "Środki bonusowe": "Bonus funds",
  "Odśwież stan konta": "Refresh account balance",
  "Ładowanie transakcji...": "Loading transactions...",
  "Brak historii transakcji": "No transaction history",
  "Opis": "Description",
  "Kwota": "Amount",
  "Zrealizowana": "Completed",
  "Oczekująca": "Pending",
  "Anulowana": "Cancelled",
  
  // Login / Auth
  "E-mail": "Email",
  "Email": "Email",
  "Hasło": "Password",
  "Zaloguj": "Log In",
  "Nie masz konta? Zarejestruj się": "Don't have an account? Sign up",
  "Masz już konto? Zaloguj się": "Already have an account? Log in",
  "Zarejestruj się": "Register",
  "Rejestracja": "Registration",
  "Imię": "First Name",
  "Nazwisko": "Last Name",
  "Zaloguj przez GitHub": "Log in with GitHub",
  "Witaj w PewniaczekBet": "Welcome to PewniaczekBet",
  "Utwórz konto i zacznij obstawiać": "Create an account and start betting",
  "Zaloguj się, aby kontynuować": "Log in to continue",
  "Masz już konto? ": "Already have an account? ",
  "Nie masz konta? ": "Don't have an account? ",
  "lub": "or",
  
  // General betting
  "Brak dostępnych zakładów dla tego sportu": "No bets available for this sport",
  "Wybierz inny sport lub sprawdź ponownie później.": "Choose another sport or check again later.",
  "Brak dostępnych zakładów dokładnego wyniku dla tego sportu": "No score bets available for this sport",
  "Brak dostępnych prediction": "No predictions available",
  "Sprawdź ponownie później.": "Check back later.",
  "Zakład Społecznościowy": "Social Bet",
  "Pula początkowa": "Initial pool",
  "Głosy": "Votes",
  "Aktualny kurs": "Current odds",
  "Stawka (PLN)": "Stake (PLN)",
  "Ew. wygrana": "Est. payout",
  "Przetwarzanie...": "Processing...",
  "Obstawi": "Bet",
  "Wygrane": "Won",
  "Przegrane": "Lost",
  "Remis": "Draw",
  "Poprzednia": "Previous",
  "Następna": "Next",
  "Strona": "Page",
  "z": "of",
  "Gorące mecze": "Hot Matches",
  "Sprawdź najciekawsze spotkania tego weekendu!": "Check out the hottest matches of this weekend!",
  "Zakłady 1X2": "1X2 Bets",
  "Dokładny Wynik": "Correct Score",
  "Polecane zakłady 1X2": "Recommended 1X2 Bets",
  "Zakłady na Dokładny Wynik": "Correct Score Bets",
  "Zakłady Prediction": "Prediction Bets",
  "Zakłady Live": "Live Bets",
  "Obstawiaj mecze na żywo z dynamicznie zmieniającymi się kursami!": "Bet on live matches with dynamically changing odds!",
  
  // Admin / Worker
  "Panel Administratora": "Admin Panel",
  "Zarządzanie": "Management",
  "Dodaj mecz": "Add Match",
  "Rozstrzygnij": "Resolve",
  "Nazwa": "Name",
  "Data": "Date",
  "Sport": "Sport",
  "Kurs": "Odds",
  "Kursy": "Odds",
  "Dodaj": "Add",
  
  // History
  "Aktywne": "Active",
  "Zakończone": "Settled",
  "Data obstawienia": "Betting date",
  "Typ": "Type",
  "Status": "Status",
  "Wygrana": "Won",
  "Przegrana": "Lost",
  "Brak zakładów w historii": "No bets in history",
  "Historia zakładów": "Betting History",
  "Wszystkie": "All",
  "Wynik": "Match Result",
  "Dokładny wynik": "Correct Score",
  "Predykcja": "Prediction",
  "Ładowanie...": "Loading...",
  "Historia zakładów jest tymczasowo niedostępna": "Betting history is temporarily unavailable",
  "Spróbuj ponownie później": "Please try again later",
  "Brak historii zakładów": "No betting history",
};

export function t(text: string): string {
  if (i18n.language && i18n.language.startsWith('en')) {
    return dictionary[text] || text;
  }
  return text;
}
